Bug_Project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app01 import views
from web import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 存在多个app时，添加namespace='app01'避免app01.urls.py内路由反向解析时name相同导致冲突。
    # url(r'^app01/', include('app01.urls',namespace='app01')),
    # web
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url, include
from web.views import account
from web.views import home
from web.views import project
from web.views import manage
from web.views import wiki

urlpatterns = [
    # 注册
    url(r'^register/$', account.register, name='register'),  # 添加name 方便反向解析
    # 短信验证
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    # 短信登录
    url(r'^login/sms/$', account.login_sms, name='login_sms'),
    # 用户登录
    url(r'^login/$', account.login, name='login'),
    # 获取图片验证码地址
    url(r'^img/code/$', account.image_code, name='image_code'),
    # 首页
    url(r'^index/$', home.index, name='index'),

    # 退出登录
    url(r'^logout/$', account.logout, name='logout'),

    # 项目列表
    url(r'^project/list/$', project.project_list, name='project_list'),
    # 添加星标 /project/star/my/1 /project/star/join/1
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    # 取消星标
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),

    # 进入项目管理
    url(r'^manage/(?P<project_id>\d+)/', include([
        url(r'^dashboard/$', manage.dashboard, name='manage_dashboard'),
        url(r'^issues/$', manage.issues, name='manage_issues'),
        url(r'^statistics/$', manage.statistics, name='manage_statistics'),
        url(r'^file/$', manage.file, name='manage_file'),
        url(r'^wiki/$', wiki.wiki, name='manage_wiki'),
        url(r'^setting/$', manage.setting, name='manage_setting'),
    ], None)),
]

app01/views.py
from django.shortcuts import render, HttpResponse
import random


# Create your views here.


def send_sms(request):
    """模拟短信发送功能"""
    code = random.randrange(1000, 9999)
    print(code)
    return HttpResponse(code)


from django import forms
from app01 import models
from django.core.validators import RegexValidator  # 正则模块
from django.core.exceptions import ValidationError  # 正则模块


class RegisterModelForm(forms.ModelForm):
    """ModelForm生成注册页面表单字段"""
    # 对手机号码字段类型重写，进行正则判断
    mobile_phone = forms.CharField(label='手机号码', validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式错误'), ])
    # 对密码字段类型重写，密码插件，展示时为密文
    password = forms.CharField(label='密码', widget=forms.PasswordInput())
    # 重复确认密码； attrs={,}属性可以添加class类样式
    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': '确认密码'}))
    # 验证码; attrs={,}属性可以添加class类样式
    # code = forms.CharField(label='验证码', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '验证码'}))
    code = forms.CharField(label='验证码', widget=forms.TextInput(attrs={'placeholder': '验证码'}))

    class Meta:
        model = models.UserInfo
        # __all__ 前端页面form字段先自动展示models内容，然后在展示RegisterModelForm 定义后的内容
        # fields = '__all__'
        fields = ['username', 'password', 'confirm_password', 'email', 'mobile_phone', 'code']  # 自定义顺序

    # 重写__init__方法，添加上默认的class类 'form-control'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            # attrs={,}属性可以添加class类样式
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = '请输入%s' % (field.label,)


def register(request):
    """注册功能"""
    form = RegisterModelForm()
    return render(request, 'app01/register.html', {'form': form})


if __name__ == '__main__':
    # send_sms(1)
    ...

web/views/wiki.py
from django.shortcuts import render


def wiki(request, project_id):
    """首页"""
    return render(request, 'wiki.html')

web/templates/dashboard.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>概览</h1>
{% endblock %}

web/templates/file.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>文件</h1>
{% endblock %}

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block css %}
    <style>
    img{
        width: 100%;
    }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static '/img/index/index-1.png' %}" alt="">
        <img src="{% static '/img/index/index-2.png' %}" alt="">
        <img src="{% static '/img/index/index-3.png' %}" alt="">
        <img src="{% static '/img/index/index-4.png' %}" alt="">
    </div>
{% endblock %}

web/templates/issues.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>问题</h1>
{% endblock %}

web/templates/login.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户登录{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {#判断如果是验证码，就添加一个按钮#}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            {#生成input框#}
                            <div class="col-md-7">
                                {{ field }}
                                {# 错误提示信息标签#}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            {#生成验证码图片#}
                            <div class="col-md-5">
                                <img src="{% url 'image_code' %}" id="imageCode" title="点击更验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {#生成input框#}
                        {{ field }}
                        {# 错误提示信息标签#}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="checkbox">
                <div style="float: right">
                    <a href="{% url 'login_sms' %}"> 短信验证码登录</a>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="submit" class="btn btn-primary btn-block" value="登  录"/>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block js %}
<script>
    {#点击刷新验证码#}
    $(function () {
        $('#imageCode').click(function () {
            var oldSrc =  $(this).attr('src');  {#获取原来的地址#}
            $(this).attr('src',oldSrc+"?");{#在原地址后面加？号，就会重新请求#}
        })
    })
</script>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}短信登录{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户短信登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {#判断如果是验证码，就添加一个按钮#}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            {#生成input框#}
                            <div class="col-md-7">
                                {{ field }}
                                {# 错误提示信息标签#}
                                <span class="error-msg"></span>
                            </div>
                            {#生成按钮#}
                            <div class="col-md-5">
                                <input id="btnSms" type="button" class="btn btn-info btn-block"
                                       value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {#生成input框#}
                        {{ field }}
                        {# 错误提示信息标签#}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="checkbox">
                <div style="float: right">
                    <a href="{% url 'login' %}"> 用户名密码登录</a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary btn-block" value="登  录"/>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block js %}
    <script>
        {#页面框架加载完后自动执行函数#}
        $(function () {
            bindClickBtnSms();
            {# 验证按钮函数 #}
            bindClickBtnSubmit();
            {# 注册按钮函数 #}
        })

        {#点击登录按钮的绑定事件#}

        function bindClickBtnSubmit() {
            {#定位按钮，点击#}
            $('#btnSubmit').click(function () {
                {#每次点击时，先清空所有的错误提示信息#}
                $('.error-msg').empty();

                {#数据ajax发送到后台#}
                $.ajax({
                    url: "{% url 'login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(), {#收集表单数据,serialize() 获取所有form表单字段的数据 + csrf token#}
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res)
                        if (res.status) {
                            {#如果注册成功，跳转。#}
                            location.href = res.data;
                        } else {
                            {#如果注册失败，展示错误信息。#}
                            $.each(res.error, function (key, value) {
                                {#取#id_"+ key 标签的下一个标签#}
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })

        }


        {#点击获取验证码按钮的绑定事件#}

        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                {#每次点击时，先清空所有的错误提示信息#}
                $('.error-msg').empty();

                {#获取用户输入的手机号，找到输入框的ID，获取内容#}
                var mobilePhone = $('#id_mobile_phone').val();
                {#发送ajax请求，手机号码#}
                $.ajax({
                    url: '{% url "send_sms" %}', {#url提交地址，urls.py使用了name，可以使用反向解析;等价于 /send/sms#}
                    type: 'GET', {# GET or POST #}
                    data: {mobile_phone: mobilePhone, tpl: 'login'}, {# 参数 #}
                    dataType: 'JSON', {# 将服务端返回的数据反序列号为字典 #}
                    success: function (res) {
                        {# ajax请求发送成功之后，自动执行的回调函数，res就是后端返回的值#}
                        {#console.log(res);#}
                        if (res.status) {
                            {#console.log('成功，倒计时');#}
                            {#定义一个函数#}
                            sendSmsRemind();
                        } else {
                            {#   status:False,error:{mobile_phone:['错误信息']}    #}
                            {# $.each() 表示循环#}
                            $.each(res.error, function (key, value) {
                                {#取#id_"+ key 标签的下一个标签#}
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        {#验证码倒计时函数#}

        function sendSmsRemind() {
            {#找到验证码按钮#}
            var $smsBtn = $("#btnSms");
            {#按钮加了 disabled属性，不可以点击操作#}
            $smsBtn.prop("disabled", true);
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    {# 定时器关闭 #}
                    $smsBtn.val('获取验证码').prop('disabled', false);
                }
            }, 1000);
            {#每隔一秒执行1次 #}
        }
    </script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% load static %}

{% block css %}
    <style>
        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid"> {#container-fluid平铺#}
        <div style="margin-bottom: 10px;">
            <a class="btn btn-primary" data-toggle="modal" data-target="#addModal">
                <i class="fa fa-plus-circle" aria-hidden="true"></i> 新键项目</a>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标</div>
            <div class="panel-body">
                {% for item in project_dict.star %}
                    <div class="item">
                        <a href="{% url 'manage_dashboard' project_id=item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的</div>
            <div class="panel-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="{% url 'manage_dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='my' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的</div>
            <div class="panel-body">
                {% for item in project_dict.join %}
                    <div class="item">
                        <a href="{% url 'manage_dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='join' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

    {# 新键项目 模态框 开始#}
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                </div>
                <div class="modal-body">

                    <form id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                        {% endfor %}
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="btnSubmit" type="button" class="btn btn-primary">确定</button>
                </div>
            </div>
        </div>
    </div>
    {# 新键项目 模态框 结束#}
{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindSubmit();
        });

        function bindSubmit() {
            $('#btnSubmit').click(function () {
                $.ajax({
                    url: '{% url 'project_list' %}',
                    type: 'POST',
                    {#.serialize()获取所有表单数据#}
                    data: $('#addForm').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        console.log(res);
                        if (res.status) {
                            location.href = location.href; //同location.reload() 刷新页面
                        } else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/register.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户注册{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in from %}
                {#判断如果是验证码，就添加一个按钮#}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            {#生成input框#}
                            <div class="col-md-7">
                                {{ field }}
                                {# 错误提示信息标签#}
                                <span class="error-msg"></span>
                            </div>
                            {#生成按钮#}
                            <div class="col-md-5">
                                <input id="btnSms" type="button" class="btn btn-info btn-block"
                                       value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        {#field.label 会去找ModelForm,ModeFrom 实际获取的是UserInfo中的verbose_name#}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {#生成input框#}
                        {{ field }}
                        {# 错误提示信息标签#}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            {# <button id="btnSubmit" type="submit" class="btn btn-primary btn-block">注 册</button>#}
            <div class="row">
                <div class="col-xs-12">
                    <input id="btnSubmit" type="button" class="btn btn-primary btn-block" value="注  册"/>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block js %}
    <script>
        {#页面框架加载完后自动执行函数#}
        $(function () {
            bindClickBtnSms();
            {# 验证按钮函数 #}
            bindClickBtnSubmit();
            {# 注册按钮函数 #}
        })

        {#点击注册按钮的绑定事件#}

        function bindClickBtnSubmit() {
            {#定位按钮，点击#}
            $('#btnSubmit').click(function () {
                {#每次点击时，先清空所有的错误提示信息#}
                $('.error-msg').empty();

                {#数据ajax发送到后台#}
                $.ajax({
                    url: "{% url 'register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(), {#收集表单数据,serialize() 获取所有form表单字段的数据 + csrf token#}
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res)
                        if (res.status) {
                            {#如果注册成功，跳转。#}
                            location.href = res.data;
                        } else {
                            {#如果注册失败，展示错误信息。#}
                            $.each(res.error, function (key, value) {
                                {#取#id_"+ key 标签的下一个标签#}
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })

        }


        {#点击获取验证码按钮的绑定事件#}
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                {#每次点击时，先清空所有的错误提示信息#}
                $('.error-msg').empty();

                {#获取用户输入的手机号，找到输入框的ID，获取内容#}
                var mobilePhone = $('#id_mobile_phone').val();
                {#发送ajax请求，手机号码#}
                $.ajax({
                    url: '{% url "send_sms" %}', {#url提交地址，urls.py使用了name，可以使用反向解析;等价于 /send/sms#}
                    type: 'GET', {# GET or POST #}
                        data: {mobile_phone: mobilePhone}, {# 参数 #}
                    dataType: 'JSON', {# 将服务端返回的数据反序列号为字典 #}
                    success: function (res) {
                        {# ajax请求发送成功之后，自动执行的回调函数，res就是后端返回的值#}
                        {#console.log(res);#}
                        if (res.status) {
                            {#console.log('成功，倒计时');#}
                            {#定义一个函数#}
                            sendSmsRemind();
                        } else {
                            {#   status:False,error:{mobile_phone:['错误信息']}    #}
                            {# $.each() 表示循环#}
                            $.each(res.error, function (key, value) {
                                {#取#id_"+ key 标签的下一个标签#}
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        {#验证码倒计时函数#}
        function sendSmsRemind() {
            {#找到验证码按钮#}
            var $smsBtn = $("#btnSms");
            {#按钮加了 disabled属性，不可以点击操作#}
            $smsBtn.prop("disabled", true);
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    {# 定时器关闭 #}
                    $smsBtn.val('获取验证码').prop('disabled', false);
                }
            }, 1000);
            {#每隔一秒执行1次 #}
        }
    </script>
{% endblock %}

web/templates/setting.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>设置</h1>
{% endblock %}

web/templates/statistics.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>统计</h1>
{% endblock %}

web/templates/wiki.html
{% extends 'layout/manage.html' %}


{% block css %}
    <style>
        {#.panel-body{#}
        {#    padding: 0;#}
        {#}#}
        {##}
        .title-list {
            border-right: 1px solid #dddddd;
            min-height: 800px;
        }

        .content {
            border-left: 1px solid #dddddd;
            min-height: 800px;
            margin-left: -1px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-book" aria-hidden="true"></i> 知识库</div>
            <div class="panel-body">
                <div class="col-md-2 title-list">
                    目录
                </div>
                <div class="col-md-9 content">
                    <div style="text-align: center; margin-top: 50px;">
                        <h4> {{ request.project.project.name }} - 文档库</h4>
                        <a href="">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i> 添加文章
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}